[pytest]
testpaths = testcase
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    smoke: 冒烟核心P0用例
    regress: 回归P1全量用例
addopts = -v --tb=short --reruns 1 -n 2
norecursedirs = venv_final config common data reports .venv